### ISSUE TITLE
double buttons

### ISSUE THREAD

**Issue by liedekef** [qTranslate-Team/events-made-easy-qtranslate-x#2]
The plugin seems to be working fine. I like the fact that you can place the language buttons on multiple places in one page, but then there's a small issue: when clicking on another language via the buttons in one place, the language buttons on another place don't reflect the new language (the content of the fields is translated ok though, so it's just a visual issue)

**Comment by johnclause** [comment]
Yes, button sets are not synchronized currently. We probably should set just one set for now? Which one would you prefer to leave?

**Comment by johnclause** [comment]
Ok, I implemented proper synchronization of LSB on the latest: https://github.com/qTranslate-Team/qtranslate-x. Could you test it? Are we ready to publish  https://wordpress.org/plugins/events-made-easy-qtranslate-x/?

**Comment by liedekef** [comment]
Well, I did locations, but I still need to do the settings. But we can continue gradually of course ...
And I need to test the new version of your plugin now :-)

**Comment by johnclause** [comment]
I think it is better to finish it all before publishing, otherwise we will have to immediately start answering support questions, which will waste some time  ...

**Comment by liedekef** [comment]
I confirm that the double buttons are synchronized, very nice! I'll continue the testing now.
